/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: 3DHaupt (https://sketchfab.com/dennish2010)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/black-dragon-with-idle-animation-fb0053a2e59b43868e934c239bf4eb36
title: Black Dragon with Idle Animation
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Dragon(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/dragon.gltf");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0}>
          <group
            name="aeeb858164ee4e0884da4001c74b8628fbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="Hemi"
                  position={[4018.55, 4666.06, 3759.08]}
                  rotation={[-2.59, 0.26, 0.39]}
                  scale={100}
                />
                <group name="Plane" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh
                    name="Plane_Material_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane_Material_0.geometry}
                    material={materials.Material}
                  />
                </group>
                <group
                  name="Dragon_Idle"
                  rotation={[Math.PI, 0, 0]}
                  scale={100}
                >
                  <group name="Object_10">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh
                      name="Object_244"
                      geometry={nodes.Object_244.geometry}
                      material={materials.EYES}
                      skeleton={nodes.Object_244.skeleton}
                    />
                    <skinnedMesh
                      name="Object_245"
                      geometry={nodes.Object_245.geometry}
                      material={materials.Game_dragon}
                      skeleton={nodes.Object_245.skeleton}
                    />
                    <skinnedMesh
                      name="Object_246"
                      geometry={nodes.Object_246.geometry}
                      material={materials["Game_dragon.001"]}
                      skeleton={nodes.Object_246.skeleton}
                    />
                  </group>
                </group>
                <group
                  name="Dragon"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/dragon.gltf");
